version: '3.8'

services:
  frontend:
    environment:
      NODE_ENV: production
      JWT_SECRET: KJhasjkdh!21287312hJHASk
      JWT_REFRESH_SECRET: JHJahsdqwe7123!98JHkjas
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: KJhasjkdh!21287312hJHASk
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: tracking_db
      DB_PORT: 3306
      NEXT_PUBLIC_BASE_URL: http://localhost:3000 
    build:
      context: ./frontend/tracking-dashboard
      dockerfile: Dockerfile
    container_name: tracking-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend-api

  backend-api:
    build:
      context: ./backend           
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "5001:5001"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: tracking_db

  mysql_db:
    image: mysql:8.3
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tracking_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - mysql_db

volumes:
  mysql_data:
